### ISSUE TITLE
Unable to deploy the stack

### ISSUE THREAD

**Issue by agiusalexandre** [Rhosys/aws-s3-explorer#16]
Unable to deploy the stack because of s3 CORS policy

**Comment by wparad** [comment]
That hopefully shouldn't be the case. Can you provide the exact error you are getting along with a link to the current deployed website that we can test going to?

**Comment by agiusalexandre** [comment]
Yes, I apologize for the limited details I provided. While deploying the SAM Resource within the CloudFormation stack creation process, specifically during the creation of the BucketForS3ExplorerSavedConfiguration resource, I encountered a 'validation failed' status with the following message: 'Properties validation failed for resource BucketForS3ExplorerSavedConfiguration with the message: [#/CorsConfiguration/CorsRules/0/AllowedOrigins: array items are not unique].

**Comment by wparad** [comment]
Great thank you. This has been fixed now. However, the problem should only happen when you haven't set a custom domain, which I assume you might actually want to do. Is there a reason that one wasn't added here? So that might be the pertinent question. But in any case this has been resolved, thank you for the report.
